import AvatarImage from "@/shared/assets/employees/avatar.svg";

export const employeeData = [
  {
    id: 1,
    name: "Arlene McCoy",
    sectionName: "Sotuv bo'limi",
    position: "Nursing Assistant",
    number: "+998 98 669 96 58",
    image: AvatarImage,
  },
  {
    id: 2,
    name: "Arlene McCoy",
    sectionName: "Sotuv bo'limi",
    position: "Nursing Assistant",
    number: "+998 98 669 96 58",
    image: AvatarImage,
  },
  {
    id: 3,
    name: "Arlene McCoy",
    sectionName: "Sotuv bo'limi",
    position: "Nursing Assistant",
    number: "+998 98 669 96 58",
    image: AvatarImage,
  },
  {
    id: 4,
    name: "Arlene McCoy",
    sectionName: "Sotuv bo'limi",
    position: "Nursing Assistant",
    number: "+998 98 669 96 58",
    image: AvatarImage,
  },
  {
    id: 5,
    name: "Arlene McCoy",
    sectionName: "Sotuv bo'limi",
    position: "Nursing Assistant",
    number: "+998 98 669 96 58",
    image: AvatarImage,
  },
  {
    id: 6,
    name: "Arlene McCoy",
    sectionName: "Sotuv bo'limi",
    position: "Nursing Assistant",
    number: "+998 98 669 96 58",
    image: AvatarImage,
  },
  {
    id: 7,
    name: "Arlene McCoy",
    sectionName: "Sotuv bo'limi",
    position: "Nursing Assistant",
    number: "+998 98 669 96 58",
    image: AvatarImage,
  },
  {
    id: 8,
    name: "Arlene McCoy",
    sectionName: "Sotuv bo'limi",
    position: "Nursing Assistant",
    number: "+998 98 669 96 58",
    image: AvatarImage,
  },
  {
    id: 9,
    name: "Arlene McCoy",
    sectionName: "Sotuv bo'limi",
    position: "Nursing Assistant",
    number: "+998 98 669 96 58",
    image: AvatarImage,
  },
  {
    id: 10,
    name: "Arlene McCoy",
    sectionName: "Sotuv bo'limi",
    position: "Nursing Assistant",
    number: "+998 98 669 96 58",
    image: AvatarImage,
  },
  {
    id: 11,
    name: "Arlene McCoy",
    sectionName: "Sotuv bo'limi",
    position: "Nursing Assistant",
    number: "+998 98 669 96 58",
    image: AvatarImage,
  },
  {
    id: 12,
    name: "Arlene McCoy",
    sectionName: "Sotuv bo'limi",
    position: "Nursing Assistant",
    number: "+998 98 669 96 58",
    image: AvatarImage,
  },
];
